### ISSUE TITLE
feature suggestion: quick plots of spectra

### ISSUE THREAD

**Issue by Shreyas-Patankar** [wincowgerDEV/OpenSpecy-shiny#12]
would be cool to have a quick way to just see what a given OpenSpecy library spectrum looks like, without needing to upload data. For example, if I just want to know what a "polyamide" spectrum looks like, in this feature I would do a simple text search for "polyamide" and be able to see a quick plot of the top 2-3 OpenSpecy entries that match the key word "polyamide"

**Comment by wincowgerDEV** [comment]
@Shreyas-Patankar check out the reviewer_app beta page and let me know if this is what you are looking for. https://wincowger.shinyapps.io/reviewer_app/

Basically now if you don't add any spectra to the tool you can select activate identification and it will start querying the library without querying spectra. Then you can use the search function to type in the name of something you want to find. It also interacts with any other features you select so if you just want to see the raman spectra you can select that in the advanced features of the identification tab.

**Comment by wincowgerDEV** [comment]
Done
